# Generated by Django 2.0.2 on 2018-04-05 15:43

from django.db import migrations, models
import django.db.models.deletion
import v1.general.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('symbol', models.CharField(db_index=True, max_length=30, unique=True)),
                ('image', models.ImageField(null=True, upload_to=v1.general.utils.coins_image_upload_to)),
                ('operational', models.BooleanField(default=False)),
                ('service_fee', models.FloatField(default=0)),
                ('decimals', models.PositiveIntegerField(default=0)),
                ('multi_withdrawal', models.BooleanField(default=False)),
                ('block_explorer_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-operational'],
            },
        ),
        migrations.CreateModel(
            name='CoinPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('rate', models.FloatField()),
                ('minerFee', models.FloatField(default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_coin', to='coins.Coin')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_coin', to='coins.Coin')),
            ],
            options={
                'ordering': ['source__symbol'],
            },
        ),
    ]
