# Generated by Django 2.0.2 on 2018-02-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('symbol', models.CharField(db_index=True, max_length=30, unique=True)),
                ('api_url', models.URLField()),
                ('api_auth', models.BooleanField(default=True)),
                ('api_username', models.CharField(max_length=32)),
                ('api_password', models.CharField(max_length=64)),
                ('deposit_endpoint', models.CharField(max_length=255)),
                ('withdraw_endpoint', models.CharField(max_length=255)),
                ('operational', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
