# Generated by Django 2.0.2 on 2018-04-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='decimals',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
