# Generated by Django 2.0.2 on 2018-02-21 15:49

from django.db import migrations, models
import v1.general.utils


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='image',
            field=models.ImageField(null=True, upload_to=v1.general.utils.coins_image_upload_to),
        ),
    ]
