# Generated by Django 2.0.2 on 2018-03-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_coin_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='api_auth',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='api_password',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='api_url',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='api_username',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='deposit_endpoint',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='withdraw_endpoint',
        ),
        migrations.AddField(
            model_name='coin',
            name='price_btc',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=24),
        ),
    ]
