# Generated by Django 2.0.2 on 2018-03-07 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_auto_20180302_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='coin',
            name='price_btc',
        ),
        migrations.AddField(
            model_name='coinpair',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_coin', to='coins.Coin'),
        ),
        migrations.AddField(
            model_name='coinpair',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_coin', to='coins.Coin'),
        ),
    ]
