# Generated by Django 2.0.2 on 2018-03-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_auto_20180307_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinpair',
            name='rate',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
    ]
