# Generated by Django 2.0.2 on 2018-03-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0005_auto_20180307_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
