# Generated by Django 2.0.2 on 2018-03-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0006_coin_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinpair',
            options={'ordering': ['-date_modified']},
        ),
        migrations.AddField(
            model_name='coin',
            name='decimals',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
