# Generated by Django 2.0.2 on 2018-03-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0007_auto_20180307_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='fee',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coinpair',
            name='rate',
            field=models.FloatField(),
        ),
    ]
