# Generated by Django 2.0.3 on 2018-03-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0009_auto_20180307_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={'ordering': ['-operational']},
        ),
        migrations.AlterModelOptions(
            name='coinpair',
            options={'ordering': ['source__symbol']},
        ),
        migrations.AddField(
            model_name='coinpair',
            name='minerFee',
            field=models.FloatField(default=0),
        ),
    ]
