# Generated by Django 2.0.2 on 2018-04-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0010_auto_20180326_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='fee_per_kb',
        ),
        migrations.AddField(
            model_name='coin',
            name='multi_withdrawal',
            field=models.BooleanField(default=False),
        ),
    ]
