# Generated by Django 2.0.2 on 2018-02-21 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coins', '0002_coin_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(db_index=True, primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(max_length=255)),
                ('rollback_wallet', models.CharField(max_length=255)),
                ('withdrawl_address', models.CharField(max_length=255)),
                ('deposit_tx_hash', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('awaiting', 'Wating for deposit'), ('deposit_received', 'Deposit transaction received'), ('exchange', 'Exchanging'), ('out_order', 'Out of order'), ('completed', 'Completed')], db_index=True, default='submitted', max_length=10)),
                ('note', models.TextField(max_length=255, null=True)),
                ('despoit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_coin', to='coins.Coin')),
                ('withdraw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawl_coin', to='coins.Coin')),
            ],
        ),
    ]
