# Generated by Django 2.0.2 on 2018-02-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20180221_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(auto_created=True, db_index=True, primary_key=True, serialize=False),
        ),
    ]
