# Generated by Django 2.0.2 on 2018-02-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20180221_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='wallet_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
