# Generated by Django 2.0.2 on 2018-02-27 21:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20180225_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
