# Generated by Django 2.0.2 on 2018-03-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20180301_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('awaiting', 'Wating for deposit'), ('deposit_received', 'Deposit transaction received'), ('waiting_for_confirmation', 'Wating for transaction confirmation'), ('exchange', 'Exchanging'), ('out_order', 'Out of order'), ('completed', 'Completed')], db_index=True, default='submitted', max_length=100),
        ),
    ]
