# Generated by Django 2.0.2 on 2018-03-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20180302_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='deposit_tx_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
