# Generated by Django 2.0.2 on 2018-03-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_transaction_deposit_tx_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='deposit_tx_index',
            new_name='deposit_tx_confirmations',
        ),
    ]
