# Generated by Django 2.0.2 on 2018-03-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20180302_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='deposit_tx_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
