# Generated by Django 2.0.2 on 2018-03-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_transaction_deposit_tx_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
