# Generated by Django 2.0.2 on 2018-03-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_transaction_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='received_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='exchange_rate',
            field=models.FloatField(default=0),
        ),
    ]
