# Generated by Django 2.0.2 on 2018-03-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_auto_20180310_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='received_amount',
            new_name='withdraw_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='withdraw_tx_hash',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
