# Generated by Django 2.0.2 on 2018-03-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_auto_20180310_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionOutputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('value', models.FloatField()),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='outs',
            field=models.ManyToManyField(related_name='transaction_outputs', to='transactions.TransactionOutputs'),
        ),
    ]
