# Generated by Django 2.0.2 on 2018-03-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_auto_20180315_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='withdraw_tx_hash',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='withdrawl_address',
        ),
        migrations.AddField(
            model_name='transactionoutputs',
            name='tx_hash',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
