# Generated by Django 2.0.3 on 2018-03-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_auto_20180315_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionoutputs',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
