# Generated by Django 2.0.3 on 2018-03-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_transactionoutputs_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionoutputs',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
