# Generated by Django 2.0.3 on 2018-03-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_transactionoutputs_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('awaiting', 'Wating for deposit'), ('deposit_received', 'Deposit received'), ('waiting_for_confirmation', 'Waiting for confirmation'), ('exchange', 'Exchanging'), ('out_order', 'Out of order'), ('completed', 'Completed'), ('refunded', 'Refunded')], db_index=True, default='submitted', max_length=100),
        ),
    ]
