# Generated by Django 2.0.2 on 2018-04-02 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_transaction_destination_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='deposit_tx_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='withdraw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_coin', to='coins.Coin'),
        ),
    ]
