# Generated by Django 2.0.2 on 2018-04-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_auto_20180402_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='deposit_tx_amount',
            field=models.FloatField(default=0),
        ),
    ]
